name: GitHub action file for CI/CD pipeline
Env:
  OUTPUT_PATH: ${{ github.workspace }}
on: [push]
jobs:
# Deploy VM in Azure
  DeployVM:
    runs-on: ubuntu-latest
steps:
    # checkout code from repo
    - name: checkout repo
      uses: actions/checkout
    - name: look for ps1 file
      run: |
        ls '${{ env.OUTPUT_PATH }}\IaC\AzCLI'
    
    - name: provision virtual machine in azure
      env:
        RESOURCE_GROUP: xxxxx
        RESOURCE_GROUP_REGION: xxxxx
        SERVER_NAME: xxxxxx
        ADMIN_LOGIN: xxxx
      run: >
        powershell -command "& '${{ env.OUTPUT_PATH }}\IaC\AzCLI\vmcreation.ps1'" 
        -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}
        -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }} 
        -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }} 
        -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        -resourceGroupName %RESOURCE_GROUP% 
        -resourceGroupNameRegion %RESOURCE_GROUP_REGION% 
        -serverName %SERVER_NAME% 
        -adminLogin %ADMIN_LOGIN% 
        -adminPassword ${{ secrets.ADMIN_PASSWORD }} 
